2023-10-08 14:26:22,292 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D7C81870>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:24,334 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D7C82260>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:26,363 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D7C823E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:30,868 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8992140>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:32,911 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8992050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:34,935 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8991CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:39,216 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8076260>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:41,242 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D80764A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:43,285 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D80767D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:47,551 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D88A7D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:49,581 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D88A5B70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:51,616 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D88A5420>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:55,884 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D896A590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:57,929 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D896A2C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:26:59,967 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8969180>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:27:04,216 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8A6E650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:27:06,243 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8A6EFB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
2023-10-08 14:27:08,283 WARNING [urllib3.connectionpool] [connectionpool.py (urlopen:871] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E6D8A6CC40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': //session
